// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import OffcanvasController from "./offcanvas_controller"
application.register("offcanvas", OffcanvasController)

import RoadmapController from "./roadmap_controller"
application.register("roadmap", RoadmapController)

import RoadmapFormController from "./roadmap_form_controller"
application.register("roadmap-form", RoadmapFormController)

import ThemesController from "./themes_controller"
application.register("themes", ThemesController)
